services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN}`)
      - traefik.http.services.backend.loadbalancer.server.port=8000
