services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend-celcat.rule=Host(`${BACKEND_DOMAIN}`)
      - traefik.http.services.backend-celcat.loadbalancer.server.port=8000

  frontend:
    build: ./frontend
    restart: always
    environment:
      - NUXT_PUBLIC_API_BASE_URL=https://${BACKEND_DOMAIN}
      - NUXT_PUBLIC_SITE_URL=https://${FRONTEND_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-celcat.rule=Host(`${FRONTEND_DOMAIN}`)
      - traefik.http.services.frontend-celcat.loadbalancer.server.port=3000
